# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6c9d02f5-f6b1-414a-8e47-8a73216b8f72";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "lazytime"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6c9d02f5-f6b1-414a-8e47-8a73216b8f72";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
      "lazytime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/6c9d02f5-f6b1-414a-8e47-8a73216b8f72";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "noatime"
      "compress=zstd"
      "lazytime"
    ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/72D0-E7B6";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
      "umask=0077"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A0DC-9DBC";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
      "umask=0077"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.dae0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
